AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Default: thisisuniquebucketname

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  MyTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageName
          AttributeType: S
      KeySchema:
        - AttributeName: ImageName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: labels

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 90
      MemorySize: 256
      Policies:
        - RekognitionDetectOnlyPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable
        - S3ReadPolicy:
            BucketName: !Ref BucketName
      Architectures:
        - x86_64
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
