version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trifood"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ncx8fdd53bem"
s3_prefix = "trifood"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
